# Load libraries
library(Seurat)
library(ggplot2)
library(patchwork)
library(tidyverse)
library(hdf5r)
library(ggsci)
library(celldex)
library(RColorBrewer)
library(SingleCellExperiment)
library(glmGamPoi)
library(reticulate)
library(DoubletFinder)
library(cowplot)
library(viridis)
library(pheatmap)
# Load Bioconductor packages if needed
library(scran)
library(SingleR)
library(BiocParallel)
